/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.main;

import com.gui.gui.GUI;
import com.gui.service.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class LibraryMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form LibraryMainMenu
     */
    public LibraryMainMenu() {
        initComponents();
    }

    // This is testing of github
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        addBooks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showBook = new javax.swing.JButton();
        updateBook = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        removeBook = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        borrowBook = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        returnBook = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel3.setText("jLabel3");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("4.");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LMS\\Main_Menu");
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MAIN MENU");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        addBooks.setBackground(new java.awt.Color(0, 0, 0));
        addBooks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addBooks.setForeground(new java.awt.Color(242, 242, 242));
        addBooks.setText("ADD BOOK");
        addBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBooks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addBooks.setMaximumSize(new java.awt.Dimension(125, 24));
        addBooks.setMinimumSize(new java.awt.Dimension(125, 24));
        addBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBooksActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("1.");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("2.");

        showBook.setBackground(new java.awt.Color(0, 0, 0));
        showBook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        showBook.setForeground(new java.awt.Color(242, 242, 242));
        showBook.setText("SHOW BOOKS");
        showBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showBook.setMaximumSize(new java.awt.Dimension(125, 24));
        showBook.setMinimumSize(new java.awt.Dimension(125, 24));
        showBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBookActionPerformed(evt);
            }
        });

        updateBook.setBackground(new java.awt.Color(0, 0, 0));
        updateBook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updateBook.setForeground(new java.awt.Color(242, 242, 242));
        updateBook.setText("UPDATE BOOK");
        updateBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBook.setHideActionText(true);
        updateBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateBook.setMaximumSize(new java.awt.Dimension(125, 24));
        updateBook.setMinimumSize(new java.awt.Dimension(125, 24));
        updateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("3.");

        removeBook.setBackground(new java.awt.Color(0, 0, 0));
        removeBook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        removeBook.setForeground(new java.awt.Color(242, 242, 242));
        removeBook.setText("REMOVE BOOK");
        removeBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeBook.setMaximumSize(new java.awt.Dimension(125, 24));
        removeBook.setMinimumSize(new java.awt.Dimension(125, 24));
        removeBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("4.");

        borrowBook.setBackground(new java.awt.Color(0, 0, 0));
        borrowBook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        borrowBook.setForeground(new java.awt.Color(242, 242, 242));
        borrowBook.setText("BORROW BOOK");
        borrowBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrowBook.setHideActionText(true);
        borrowBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrowBook.setMaximumSize(new java.awt.Dimension(125, 24));
        borrowBook.setMinimumSize(new java.awt.Dimension(125, 24));
        borrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBookActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("5.");

        returnBook.setBackground(new java.awt.Color(0, 0, 0));
        returnBook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        returnBook.setForeground(new java.awt.Color(242, 242, 242));
        returnBook.setText("RETURN BOOK");
        returnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        returnBook.setMaximumSize(new java.awt.Dimension(125, 24));
        returnBook.setMinimumSize(new java.awt.Dimension(125, 24));
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("6.");

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(242, 242, 242));
        logout.setText("LOG OUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setMaximumSize(new java.awt.Dimension(125, 24));
        logout.setMinimumSize(new java.awt.Dimension(125, 24));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("7.");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(borrowBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(showBook, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(removeBook, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(returnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void addBooksActionPerformed(java.awt.event.ActionEvent evt) {                                         
        new AddBook().setVisible(true);
        this.dispose();
        
    }                                        

    private void showBookActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            new ShowBook().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(LibraryMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }                                        

    private void updateBookActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try{
            new UpdateBook().setVisible(true); 
                        this.dispose();

        }catch(SQLException s){
            Logger.getLogger(LibraryMainMenu.class.getName()).log(Level.SEVERE, null, s);
        }
    }                                          

    private void removeBookActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        try{
            new RemoveBook().setVisible(true);
                        this.dispose();

        }catch(SQLException e){
            Logger.getLogger(LibraryMainMenu.class.getName()).log(Level.SEVERE, null, e);
        }
    }                                          

    private void borrowBookActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        try{
            new BorrowBook().setVisible(true);
                        this.dispose();

        }catch(SQLException s){
            Logger.getLogger(BorrowBook.class.getName()).log(Level.SEVERE, null, s);
        }
    }                                          

    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new Return().setVisible(true);
        this.dispose();
    }                                          

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        this.dispose();
        new GUI().setVisible(true);
//        System.exit(0);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryMainMenu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton addBooks;
    private javax.swing.JButton borrowBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logout;
    private javax.swing.JButton removeBook;
    private javax.swing.JButton returnBook;
    private javax.swing.JButton showBook;
    private javax.swing.JButton updateBook;
    // End of variables declaration                   

    private static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
